---
title: "Julián Mauricio Cruz Pulido"
# output-dir: _other # No funciona 
format: 
  pdf:
    include-in-header:
      - text: |
          \usepackage{marvosym}
    output-file: "Cruz-Julian_CV-muy-corta.pdf"
    classoption: [twocolumn, landscape]
    mainfont: Roboto-Thin
    colorlinks: true
    # linkcolor: ppp # No funciona
    geometry:
      - top=15mm
      - right=10mm
      - bottom=10mm
      - left=15mm

---

\Letter: cruz.julian.mauricio@gmail.com, \ComputerMouse: [Cruz Julian](https://cruzjulian.github.io/portafolio), [CVLAC](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001399375), [ORCID](https://orcid.org/0000-0002-4407-6184), [Google Scholar](https://scholar.google.es/citations?user=sDpkM20AAAAJ&hl=es), [LinkedIn](https://co.linkedin.com/in/cruzjulian)


```{r, echo=FALSE}
library("magrittr")
library("knitr")
library("readr")
library("stringr")

opts_chunk$set(echo = FALSE)

carpeta_contenidos <- "_esp-input"

archivos <- dir(
      carpeta_contenidos, 
      pattern = "qmd$"
      )

file.path(
    carpeta_contenidos, 
    archivos
    ) %>% 
#   extract(-2) %>% 
  lapply(read_lines) %>% 
  lapply(extract, -2) %>%
  lapply(str_replace_all, "[*]", "") %>% 
  setNames(archivos) -> childs

childs$laboral.qmd <- childs$laboral.qmd[5:24]
childs$docente.qmd <- childs$docente.qmd[c(34:47)]
childs$formacion.qmd <- childs$formacion.qmd[c(5:7, 9:13, 48:65)]

```

```{r}
set.seed(123456789)

emo::ji("mail") -> emoji_mail

```

```{r, results="asis"}
res <- knit(text = childs[["perfil.qmd"]], quiet = TRUE)
cat(res, sep = '\n')

```


# Experiencia laboral

```{r, results="asis"}
res <- knit(text = childs[["laboral.qmd"]], quiet = TRUE)
cat(res, sep = '\n')

```

# Experiencia docente

```{r, results="asis"}
res <- knit(text = childs[["docente.qmd"]], quiet = TRUE)
cat(res, sep = '\n')

```

# Formación

```{r, results="asis"}
res <- knit(text = childs[["formacion.qmd"]], quiet = TRUE)
cat(res, sep = '\n')

```


# Referencias y soportes

Las referencias laborales y personales, como los soportes serán remitidos a solicitud de las partes interesadas.



