---
title: "Background"
---

***

## Education

- Degree on Management. Universidad Externado de Colombia. Currently.

- M.Sc. Statistics, master thesis: [Aplicación de Algoritmos de Agrupamiento a Funciones de Distribución Empírica](https://repositorio.unal.edu.co/handle/unal/64015){target="_blank"}. National University of Colombia. September of 2018.

- Statistics, disertation: Estimación Heurística de Medidas de Probabilidad Mediante Mixturas. Universidad Nacional de Colombia. May of 2015.

***

## Software skills

 - Expert: R
 
 - Advanced: Microsoft Office (Word, Excel, Power Point); Inkscape.
 
 - Basic: SQL, Python, HTML5, CSS3, PHP, LaTeX, Java, C++, Blender, Linux, Bash, Docker.

## Languages

 - English: B1 (Examen de Estado de Calidad de la Educación Superior, Saber Pro 2013)

***

## Publications

- Yepes, G., Cruz, J., Camarena, J., et.al. (2023). [Institutionalization of corporate bribery: a measurement proposal with evidence from a Latin American sample](https://www.emerald.com/insight/content/doi/10.1108/ARLA-04-2022-0099/full/html?utm_source=smc_email_onboarding&utm_medium=email&utm_campaign=apa_author_journals_access_2023-6-14){target="_blank"}. _Emerald Insight_.
- Yepes, G., Cruz, J., Camarena, J. (2023). [Chapter 10: Who Pays for Corporate Social Responsibility?: Proposal for an Externalization Index of CSR Costs](https://link.springer.com/book/10.1007/978-3-031-10437-4){target="_blank"}. _Springer._
- Yepes, G., Bello, C., Cruz, J., Camarena, J. (2021). [Capítulo 4: El modelo pentadimensional aplicado a las empresas de Bogotá, Colombia](https://bdigital.uexternado.edu.co/server/api/core/bitstreams/bbf36c2b-9e0f-4f0d-a7a7-dff7b94777cc/content){target="_blank"}. _Universidad Externado de Colombia._
- Arias, N., Cruz, J., & Rincón, W. (2021). [Diferencia de logro geolocalizado en educación presencial y a distancia en Colombia](https://redie.uabc.mx/redie/article/view/3711){target="_blank"}. _Revista Electrónica de Investigación educativa REDIE._
- Arias, N., & Cruz, J. (2021). [Temas de investigación sobre competencias de profesores en iniciativas de actores externos en escuelas colombianas de educación básica y media](https://journal.poligran.edu.co/index.php/poliantea/article/view/2337/2209){target="_blank"}. _Poliantea._
- Cruz, J,. & Mendoza, F., (2021). [The market segmentation of higher education in Colombia reveals social inequalities](https://www.tandfonline.com/doi/pdf/10.1080/2331186X.2021.1877885?needAccess=true){target="_blank"}. _Cogent Education._
- Cruz, J,. Fonseca,. V., (2020). [Interpreting the model is for humans, not for computers](https://towardsdatascience.com/interpreting-the-model-is-for-humans-not-for-computers-9a857011ff3){target="_blank"}. _Towards Datascience._
- Cruz, J., Yepes, G., et.al. (2019) [Estado de las prácticas empresariales contra el soborno: primer estudio latinoamericano](https://www.pactoglobal-colombia.org/images/PDFs/LIBRO_Estudio_Antisoborno_2019.pdf){target="_blank"}. _Icontec Internacional._ ISBN:  978-958-56842-3-2.
- Bustos, L., Cruz, J., Yepes, G., et.al. (2019). [Chapter 16: International CSR Policies in the Mining Sector and Their Implementation in Colombia.](https://store.lexisnexis.ca/en/categories/shop-by-jurisdiction/federal-13/extractive-industries-and-human-rights-in-an-era-of-global-justice-new-ways-of-resolving-and-preventing-conflicts--skusku-cad-6722/details){target="_blank"}. _LexisNexis Canada._
- Arias, N., Cruz, J., & Rincón, W. (2018). [Women and Men's Performace in Face-to-face, Virtual and Distance Higher Education in Colombia](https://journal.poligran.edu.co/index.php/panorama/article/download/1142/1039){target="_blank"}. _Revista Panorama, 12(22), 58-69._ DOI: [http://dx.doi.org/10.15765/pnrm.v12i22.1142](http://dx.doi.org/10.15765/pnrm.v12i22.1142){target="_blank"}.
- Cruz, J., Yepes, G., (2018)[Corrupción en Colombia: El soborno corporativo como institución](https://publicaciones.uexternado.edu.co/corrupcion-en-colombia-tomo-3-corrupcion-privada-politica-colombiana.html){target="_blank"}. Universidad Externado de Colombia. ISBN 978-958-772-880-4.
- Arias, N., Cruz, J., & Rincón, W. (2017). [Factores asociados al logro educativo en estudiantes de Ciencias Económicas en modalidad presencial y a distancia en Colombia](http://hemeroteca.unad.edu.co/index.php/memorias/article/view/2890){target="_blank"}. _III Congreso Mundial de Educación Superior a Distancia._
- Cruz, J., Yepes, G., et.al. (2015). [Estado de la Responsabilidad Social Empresarial en Colombia](http://administracion.uexternado.edu.co/PRME/memorias/Entorno%20de%20los%20Negocios%20N%2020.pdf){target="_blank"}. _Avances de Entorno de los Negocios. N° 20, ISSN 1794 – 791X._ Universidad Externado de Colombia.

***

## Learning projects and acknowledgments

 - 20+ certifications on different topics of technological management and digital transformation, [Platzi](https://platzi.com/){target="_blank"}.
 - 3rd International Congress "Estudios en Organizaciones Públicas, Privadas y Sociales en América Latina y El Caribe". Presentation: _Logro Educativo y Evidencias de sus posibles Factores Asociados en Estudiantes de Ciencias Económicas en Modalidadd Presencial y Virtual_, with Nicolás Arias and William Rincón.
 - R package: _[Saber](https://github.com/nebulae-co/saber){target="_blank"}_, with Daniel Moreno and Adriana Clavijo: 
 - R package: _[Colmaps](https://github.com/nebulae-co/colmaps){target="_blank"}_, with Daniel Moreno and Adriana Clavijo. 
 - 25 Simposio Internacional de Estadística 2015. Presentation: _[Un micro-mapa de Colombia](http://nebulae-co.github.io/colmaps/micromapa){target="_blank"}_, with Daniel Moreno and Adriana Clavijo.
 - 24 Simposio Internacional de Estadística 2014. Presentation: _Uso De Metaheurísticas en Estimación Nadaraya-Watson con Aplicación a Cirugía Refractiva_.
 - 24 Simposio Internacional de Estadística 2014. Presentation: _Algoritmos de Agrupación en Diseño de Experimentos. Una Propuesta No Paramétrica_.
 - National best score by career in Saber Pro test, 2013.
 - Full scholarship at Universidad Nacional de Colombia for best entrance score, 2009.
 - Best score in ICFES exam in his promotion and Honorable Mention for artistic development, 2002.
 
***

```{r, child="footer.rmd"}
```

