---
title: "Consulting"
---

***

In this section, some projects executed as freelancer are presented.

***

## Universidad Externado de Colombia

**Software design and development.** Management of the design and development of the Corporate Social Responsibility platform 3SC4L4. Complete project management, team conformation, requirements gathering, backlog, user stories, minimum viable product and subsequent iterations.

The final product can be accessed at [3sc4l4.co](https://www.3sc4l4.co/){target="_blank"}


Project data:

 - Role: Project manager
 - Client: [First Steps in Corporate Social Responsibility Program](https://www.uexternado.edu.co/administracion-de-empresas/programa-primeros-pasos-en-responsabilidad-social-empresarial/){target="_blank"}
 - Client (representative): [Gustavo Yepes](https://www.linkedin.com/in/gustavoyepes-lopez-82049713/){target="_blank"}.
 - Contact: gustavo.yepes@uexternado.edu.co

***

## Platzi

**Statistical Inference Course.** Design of the syllabus, presentations, readings, codes and other related materials.

It is possible to access the final product in [Inferential Statistics with R](https://platzi.com/cursos/inferential-statistics/){target="_blank"}.

Project data:

 - Role: Teacher
 - Client (representative): [Enrique Devars](https://www.edevars.com/){target="_blank"}.
 - Contact: devars@platzi.com
 - July 2020.

***


## Instituto Politécnico Grancolombiano

**Consulting in data mining.** Design and development of a system of distances between subjects for the optimization of the portfolio of subjects in the framework of upgrades in the institutional platform.

Project data:

 - Role: Specialized Statistical Consultant
 - Cilent (representative): [Ana Cristina Miranda](https://www.linkedin.com/in/ana-cristina-miranda-cárdenas-20273b114/){target="_blank"}.
 - Contact: amiranda@poligran.edu.co.
 - February 2018 - April 2018.

**Statistical consulting in research.** Methodological design, information collection and statistical analysis, visualization and study's results interpretation [The market segmentation of higher education in Colombia reveals social inequalities](https://www.tandfonline.com/doi/pdf/10.1080/2331186X.2021.1877885?needAccess=true){target="_blank"}.

Project data:

 - Role: Specialized Statistical Consultant
 - Client (representative): [Frederick Andrés Mendoza](https://www.linkedin.com/in/frederick-andres-mendoza-lozano-7a773133/){target="_blank"}.
 - Contact: famendozal23@gmail.com
 - May 2017 - August 2017.

**Statistical consultancy in research** Methodological design, information collection and statistical analysis for the study _Educational Achievement in Students of Economic Sciences in Face-to-face and Virtual Higher Education_. Winning project at [ICFES 2015 Call](https://www.icfes.gov.co/web/guest/resultados-de-investigaciones-2015){target="_blank"}.

Project data:

 - Role: Specialized Statistical Consultant
 - Client (representative): [Nicolás Arias](https://www.linkedin.com/in/nicolas-arias-velandia-706719ab/){target="_blank"}.
 - Contact: nariasv@poligran.edu.co
 - August 2016 - December 2016.
 
***

## Fundación para la Educación y el Desarrollo Social FES - Ministry for the Information and Communication Technologies

**Multidimensional Regional Digital Divide Index.** Methodological design, household survey, analysis of indicators, design of a multidimensional index for the Regional Digital Divide Closure Project study.

Project data:

 - Role: Researcher
 - Client (representative): [Diana María Duarte](https://www.linkedin.com/in/diana-duarte-g%C3%B3mez-301a88116/){target="_blank"}.
 - Contact: dm.duarte29@uniandes.edu.co
 - January 2018 - July 2018.

***

## Internet Services Latam

**Specialized Statistical Consultancy.** Design and development of a demand forecast model SKU/time/location for the Mercadoni app. Preparation and analysis of historical retail sales data; conceptualization of the Parzen Window model for demand, development of the code and implementation of the model.

Project data:

 - Role: Specialized Statistical Consultant
 - Client (representative): [Daniel Moreno](https://www.linkedin.com/in/demorenoc/){target="_blank"}.
 - Contact: troybros@gmail.com
 - December 2017 - January 2018.

***

## Power Data

**Churn forecast models for Claro Hogares.** Planning and direction in measurement and forecasting processes for the Analytics area. Design, fitting, estimation and implementation of statistical, machine learning and data mining models and algorithms.

Project data:

 - Role: Senior Consultant
 - Client (representative): [Nicolás Aristizabal](https://www.linkedin.com/in/niaristizaballo/){target="_blank"}.
 - nicolas.aristizabal.eci@gmail.com
 - November 2015 - March 2016
 
***

```{r, child="footer.rmd"}
```

