---
title: "Research"
---

***

Since 2011, continuous and independent research statistical consultancy work has been carried out aiming at facing problems from different areas and providing answers from data analysis to research questions of various kinds.

***

### [Influence of the technological level on the productivity and competitiveness of beekeepers in Cundinamarca](https://repositorio.unal.edu.co/handle/unal/81283){target="_blank"}

Rodrigo Chaves Ladino. \Letter rochavesl@unal.edu.co

Degree thesis to qualify for the Master's degree in Management and Rural Development. School of Agricultural Sciences. Universidad Nacional de Colombia. 2022.

***

### Estimated net direct medical costs of breast cancer care in the general health social security system in Colombia

José Ricardo Urrego Novoa. \Letter jrurregon@unal.edu.co

Degree thesis to qualify for the title of PhD. in Pharmaceutical Sciences. Universidad Nacional de Colombia. 2020.

***

### Articulation of secondary education with higher education in Bogotá Colombia: pedagogical implications in the local context

Elias Rivero Botello. \Letter elriver13@hotmail.com

Degree thesis to qualify for the title of PhD. in education. UNAD. 2019.

***

### [Risk sexual behaviors in university students: social representations and sexual satisfaction](https://repositorio.unal.edu.co/handle/unal/76716){target="_blank"}

Heidi Marcela Castro Hernandez. \Letter hmcastroh@unal.edu.co

Degree thesis for Master's in Clinical Psychology. Universidad Nacional de Colombia. 2019.

***

### [Cost-effectiveness of aggressive treatment of early rheumatoid arthritis with conventional disease-modifying drugs compared with tumor necrosis factor alpha inhibitors in a cohort of Colombian patients](https://repositorio.unal.edu.co /handle/unal/63676){target="_blank"}

Jorge Augusto Diaz. \Letter jadiazr@unal.edu.co

Degree thesis to qualify for the title of PhD. in Pharmaceutical Sciences. Universidad Nacional de Colombia. 2017.

***

### [Evaluation of the performance factor of judges in Colombia](https://repository.unilibre.edu.co/handle/10901/11431){target="_blank"}

Omar Edgar Borja Soto. \Letter oborjas2502@gmail.com

Master's degree thesis in Administrative Law, Universidad Libre de Colombia. 2016.

***

### Relationship between the higher education academic program studied by young people from Bogotá between 18 and 24 years old and their attitude towards saving, indebtedness and money
   
Helenora Sanchez Castillo. \Letter heleonora.sanchezc@konradlorenz.edu.co
   
Degree work to opt for a Master's degree in Consumer Psychology. Fundación Universitaria Konrad Lorenz. 2016.

***

### Impact of training on the performance and perception of quality of work life of the Administrative Career and Free Appointment and Removal of the Ministry of National Education

Lesly Andrea Prieto Huérfano and Diana Carolina Hernández Gualdrón. \Letter dc.arte81@gmail.com

Degree work to opt for a Master's degree in Corporate Social Management, Universidad Externado de Colombia. 2015.

***

### Model of socio-technological cycles for socially and environmentally responsible products. Case: Intensive cutting of roses with human energy

Gabriel Garcia Acosta. \Letter ggarciaa@unal.edu.co

Degree work to opt for the title of Doctor in Technological Innovation Projects in Product and Process Engineering, Universitat Politècnica de Catalunya. 2015.

***

### Corporate Social Responsibility in Colombia: Characterization of CSR Practices against the Theory of Social Costs and their Relationship with the Business

Gustavo Yepez. \Letter gyepesl@gmail.com

Degree work to opt for the title of Doctor of Business Sciences, Antonio de Nebrija University. 2015.

***

### [Evaluation of the effects of FCS-304 in rodent models of depression](https://repositorio.unal.edu.co/handle/unal/54369){target="_blank"}

Laura Mercedes Moreno Hernandez. \Letter lmmorenoh@unal.edu.co

Degree work to opt for the M.Sc. in Pharmacology, Universidad Nacional de Colombia. 2015

***

### Integration of occupational health and safety management in social responsibility

Case study in five companies from Bogotá.

Carolina Hernandez Macias. \Letter ing_carolinahernandezm@yahoo.com

Degree work to opt for the title of Master in Health and Safety at Work, Universidad Nacional de Colombia. 2015.

***

### A mathematical description of the evolutionary turnover of tRNAs in the genus Drosophila

Liliana Constance Romero.

Degree work to opt for the title of Master of Science - Applied Mathematics, Universidad Nacional de Colombia. 2014.

***

### Refraction in infants aged 6 to 12 months using the non-cyclopegic and cyclopegic technique with tropicamide 1% cyclopentolate 1%, study conducted in Bogota 2012-2014

Natalie Gutierrez. \Letter natamu89@hotmail.com

Degree work to opt for the title of Magister in Vision Sciences, Universidad de La Salle. 2014.

***

### [Impact of the palm heart harvest on the population structure and dynamics of Euterpe oleracea in the Colombian Pacific Coast](http://library.wur.nl/WebQuery/wurpubs/490413){target="_blank"}

Martha Isabel Vallejo. \Letter mivallejoj@unal.edu.co

Degree work to opt for the title of PhD in Sciences - Biology, Universidad Nacional de Colombia. 2013.

***

### Accelerometric findings before, during and after ethanol exposure in patients with essential tremor

Lorraine Arroyo. \Letter lunawitch8@hotmail.com

Degree work to opt for the title of Master in Neurosciences, Universidad Nacional de Colombia. Meritorious thesis. 2013.

***

### Changes in symptoms, tear film and ocular surface after treatment with cyclosporine 1% and carboxymethylcellulose 0.5%, in moderate and severe dry eye syndrome

Alejandra Mendivelso Suarez. \Letter alejaam10@hotmail.com

Degree work to opt for the title of Magister in Vision Sciences, Universidad de La Salle. 2013.

***

### [Relationship between intimate partner violence against women and the appearance of postpartum depression](https://repositorio.unal.edu.co/handle/unal/11473){target="_blank"}

Edna Janneth Ramírez Bonilla. \Letter nursedna@hotmail.com

Thesis presented as a requirement to qualify for the Master's degree in Nursing. Universidad Nacional de Colombia. 2012.

***

### Urinary tract infection: cost-disease study and demographic characterization in a third level clinic in Chía, Colombia

Hernando Andres Olaya MD. Mauricio Hernandez Quintana MD. \Letter maoherqui@hotmail.com

Master's Thesis in Pharmacology presented at Universidad de la Sabana. 2011.

***

### [Evaluation of corneal and ocular aberrations by means of the high-order RMS index with two aspherical soft contact lenses in patients with low myopic astigmatism](https://docplayer.es/docview/70/63889504/#file= /storage/70/63889504/63889504.pdf){target="_blank"}

Elizabeth Suarez Piscotti. Natalie Rodriguez. \Letter natamu89@hotmail.com

Undergraduate thesis in Optometry presented at Universidad de la Salle. 2011.

***

```{r, child="footer.rmd"}
```

