---
title: "Teaching"
---

***

**Postgraduate and continuing education professor.** This work enhances the complete deploying of courses in postgaduate and continuing education programs by designing, building and teaching such courses, including pedagogical materials and evaluation tools.

 - _Investigación cuantitativa de mercados._ Course of the Marketing Master Program of the Business School from Universidad Externado de Colombia. 2020.
 - _Analítica de negocios._ Course of the Strategic Managing of Technologies Master Program of the Business School from Universidad Externado de Colombia. 2020.
 - _Elaboración de informes estadísticos._ Course designed for District Oversight Office employees. Continuing Education Office, School of Economic Sciences. Universidad Nacional de Colombia. 2019.
 - _Minería de Datos._ Course designed for Agrarian Bank employees. Continuing Education Office, School of Economic Sciences. Universidad Nacional de Colombia. 2019.
 - _Minería de Datos._ Course taught as part of the continuing education program [Diplomado en Inteligencia de Mercados](http://www.fce.unal.edu.co/media/files/PEC/cursos/Diplomados_2019/ficha_diplomado_inteligencia_de_mercados.pdf){target="_blank"}. Continuing Education Office, School of Economic Sciences. Universidad Nacional de Colombia. 2019.
 - _Analítica de datos en mercadeo._ Course taught as part of the continuing education program [Diplomado en Inteligencia de Mercados](http://www.fce.unal.edu.co/media/files/PEC/cursos/Diplomados_2019/ficha_diplomado_inteligencia_de_mercados.pdf){target="_blank"}. Continuing Education Office, School of Economic Sciences. Universidad Nacional de Colombia. 2019.
 - _Introducción a R._ Course taught as part of the continuing education program [Diplomado de Procesamiento y Análisis de Datos](http://www.fce.unal.edu.co/media/files/PEC/cursos/cursos_2019/Ficha_procesamiento_y_analisis_de_datos_15012019.pdf){target="_blank"}. Continuing Education Office, School of Economic Sciences. Universidad Nacional de Colombia. 2019.
 
***

```{r, child="footer.rmd"}
```

