---
title: "Work Experience"
---

***

## Universidad Nacional de Colombia

**Management of Data Science and Business Intelligence Programs.** Design of learning curriculum, selection of content, teachers and materials for each course. Coordination of schedules, spaces, software and implementation details.

Strategic analysis of the market and communication channels. Implementation of a student-centered immersive learning experience.

It is possible to access the different versions of the diploma at:

 - [Diplomado de Análisis de datos](http://www.fce.unal.edu.co/media/files/PEC/Formacion_a_escala/2019/III_TRIMESTRE/ficha_analisis_de_datos.pdf){target="_blank"}: October 2019 - December 2019.
 - [Diplomado de Ciencia de datos](http://www.fce.unal.edu.co/media/files/PEC/Diplomados_2020/Diplomado_en_Ciencia_de_Datos.pdf){target="_blank"}: September 2020 - December 2020.
 - [Diplomado de Ciencia de datos](http://www.fce.unal.edu.co/media/files/PEC/Diplomados_2021/Ciencia_de_Datos_VFA1S.pdf){target="_blank"}: February 2021 - June 2021.

Project data:

 - Role: Program manager
 - Immediate boss: Sandra Marín Pino.
 - Contact: proypec_fcebog@unal.edu.co.
 - August 2019 - Actualmente

***

## Universidad Externado de Colombia

**Statistical consultancy in research.** Methodological design, data collection, estimation of parameters, sample sizes, form design, survey development, web platform development, sample design and quantitative analysis, among others, for the studies:

 - Index of Institutionalization of Bribery in Latin America and the Caribbean. Published in the book [State of business practices against bribery: first Latin American study](https://www.pactoglobal-colombia.org/images/PDFs/LIBRO_Estudio_Antisoborno_2019.pdf){target="_blank"}.
 - National Transparency Study 2018. Report published by Transparency for Colombia.
 - Corporate Bribery as an Institution. Published in the book [Corruption in Colombia](https://publicaciones.uexternado.edu.co/corrupcion-en-colombia-tomo-3-corrupcion-privada-politica-colombiana.html){target="_blank"}.
 - National Transparency Study 2016. Report published by Transparency for Colombia.

Additionally, brief interventions and collaborations for some Master's theses and research articles.
 
 - Role: Professor
 - Immediate boss: [Gustavo Yepes](https://www.linkedin.com/in/gustavoyepes-lopez-82049713/){target="_blank"}
 - Contact: gustavo.yepes@uexternado.edu.co
 - April 2016 - December 2022.

***


## Colombian Ministry of Information Technology and Communications

**Management of the Data Science team.** Start-up of the analytics procedure. Proposal, execution, evaluation and feedback of Data Science projects for the analysis of the information contained in the information systems that incorporate the use of analytical tools for large volumes of information (Big Data), in compliance with all the related with legal, contractual and regulatory obligations of the companies that provide mobile, non-mobile, television, sound broadcasting and postal services.

 - Role: Head of Data Science
 - Immediate boss: Nicolás Almeyda
 - Contact: nalmeyda@mintic.gov.co
 - August 2020 - December 2021.

***

## Colmena Occupational Risk Insurer

**Statistical advice on occupational health and safety for Sanitas Internacional.** Implementation of information systems, database design, data collection and analysis of occupational medical cases and measurement of occupational health impact indicators. Advice to 3 Epidemiological Surveillance Systems: Psychosocial, Ergonomic and Biological Risk, and implementation of algorithms to identify frequent absenteeism.

 - Role: Project Prevention Advisor
 - Immediate boss: [Mario Garzón](https://www.linkedin.com/in/mario-garz%C3%B3n-lawton-82207a25/){target="_blank"}
 - Contact: mfgarzon@colsanitas.com
 - February 2014 – February 2015

***

## Optilaser

**Statistical consulting in research.** Methodological design, statistical analysis, visualization and interpretation of quantitative results in visual health.

 - Role: Statistical advisor in scientific research.
 - Immediate boss: [María Victoria Báez](https://www.linkedin.com/in/mar%C3%ADa-victoria-b%C3%A1ez-gonz%C3%A1lez-34149848/){target="_blank "}
 - Contact: vicky.baez@optilaser.com.co
 - June 2011- January 2013

***

```{r, child="footer.rmd"}
```

