---
title: "Formación"
---

***

## Educación

- Especialización en Gerencia. Universidad Externado de Colombia. En curso.

- M.Sc. Estadística, Tesis de grado: [Aplicación de Algoritmos de Agrupamiento a Funciones de Distribución Empírica](https://repositorio.unal.edu.co/handle/unal/64015){target="_blank"}. Universidad Nacional de Colombia. Grado en septiembre de 2018.

- Estadística, Tesis de grado: Estimación Heurística de Medidas de Probabilidad Mediante Mixturas. Universidad Nacional de Colombia. Grado en mayo de 2015.

- 20+ certificados [Platzi](https://platzi.com/){target="_blank"} en distintos cursos sobre desarrollo tecnológico y transformación digital en empresas. Entre otros: [Emprendimientos Sociales y Oportunidades de Negocio](https://platzi.com/p/cruz-julian/curso/2625-emprendimiento-negocio/diploma/detalle/){target="_blank"}, [Responsabilidad Social Empresarial](https://platzi.com/p/cruz-julian/curso/2501-responsabilidad-social-empresarial/diploma/detalle/){target="_blank"}, [Empredimiento Social](https://platzi.com/p/cruz-julian/curso/2785-emprendimiento-thinking/diploma/detalle/){target="_blank"}, [Introducción a la Transformacion Digital](https://platzi.com/p/cruz-julian/curso/2375-transformacion-digital/diploma/detalle/){target="_blank"}, [Business Model Canvas](https://platzi.com/p/cruz-julian/curso/1309-canvas/diploma/detalle/){target="_blank"}, [Innovación Empresarial](https://platzi.com/p/cruz-julian/curso/2674-innovacion-empresarial/diploma/detalle/){target="_blank"}, [Innovación para el Futuro y Coolhunting](https://platzi.com/p/cruz-julian/curso/1778-coolhunting/diploma/detalle/){target="_blank"}, [Modelos de Negocio](https://platzi.com/p/cruz-julian/curso/2583-modelos-negocio/diploma/detalle/){target="_blank"}, [Técnicas de Negociación](https://platzi.com/p/cruz-julian/curso/1482-tecnicas-negociacion/diploma/detalle/){target="_blank"}, [Trabajo Remoto](https://platzi.com/p/cruz-julian/curso/1872-teletrabajo-trabajo-remoto/diploma/detalle/){target="_blank"}, [Google Suite](https://platzi.com/p/cruz-julian/curso/1401-google-suite/diploma/detalle/){target="_blank"}, [Tecnología para Gerentes y Directores](https://platzi.com/p/cruz-julian/curso/1882-tecnologia-gerentes/diploma/detalle/){target="_blank"}, [Conversion Rate Optimization](https://platzi.com/p/cruz-julian/curso/8034-cro/diploma/detalle/){target="_blank"}, [Design Sprint](https://platzi.com/p/cruz-julian/curso/1702-design-sprint/diploma/detalle/){target="_blank"}, [Design Thinking](https://platzi.com/p/cruz-julian/curso/1210-design-thinking/diploma/detalle/){target="_blank"}, [Thick Data en Negocios](https://platzi.com/p/cruz-julian/curso/1928-curso-de-thick-data/diploma/detalle/){target="_blank"}, [Estadística Computacional con Python](https://platzi.com/p/cruz-julian/curso/1835-programacion-estocastica/diploma/detalle/){target="_blank"}, [Pensamiento Probabilístico](https://platzi.com/p/cruz-julian/curso/1841-probabilistica/diploma/detalle/){target="_blank"}, [Introducción a Machine Learning](https://platzi.com/p/cruz-julian/curso/2459-machine-learning/diploma/detalle/){target="_blank"}, [Visualización de Datos para Business Intelligence](https://platzi.com/p/cruz-julian/curso/2195-visualizacion-datos/diploma/detalle/){target="_blank"}, [Redes Neuronales con PyTorch](https://platzi.com/p/cruz-julian/curso/7693-pytorch/diploma/detalle/){target="_blank"}.





***

## Manejo de tecnologías

 - Avanzado: Linux, R.
 
 - Estándar: Python, SQL, JSON, Linux, Docker, GCP, Bash.
 
 - Básico: PHP, LaTeX, Java, C++.
 

## Manejo de idiomas

 - Inglés: B1 (Examen de Estado de Calidad de la Educación Superior, Saber Pro 2013)
 - Inglés: C2 ([EF SET English Certificate 72/100. C2 Proficient. Enero 2023](https://www.efset.org/cert/yMegHW){target="_blank"})


***

## Publicaciones

- [Observaciones con respecto a la ciencia abierta](https://revistas.uexternado.edu.co/index.php/contad/article/view/9933/17422){target="_blank"} carta al editor en la revista [Apuntes contables](https://revistas.uexternado.edu.co/index.php/contad/){target="_blank"}. Universidad Extenado de Colombia. 2025.
- [Does CSR Contribute to Sustainable Development? Characterization of CSR in Colombian Companies](https://link.springer.com/chapter/10.1007/978-3-031-81469-3_4){target="_blank"}, en el libro [Integrating Environmental Sustainability and Corporate Social Responsibility: A Move Beyond Profit](https://link.springer.com/book/10.1007/978-3-031-81469-3){target="_blank"}, con Gustavo Yepes y José Luis Camarena. Springer. 2025.
- [Are Firms Strategically Engaging in CSR? An Exploratory Study of SCSR Dimensions in an Emerging Market](https://link.springer.com/chapter/10.1007/978-3-031-81469-3_6){target="_blank"}, en el libro [Integrating Environmental Sustainability and Corporate Social Responsibility: A Move Beyond Profit](https://link.springer.com/book/10.1007/978-3-031-81469-3){target="_blank"}, con Gustavo Yepes y José Luis Camarena. Springer. 2025.
- [Is corporate bribery institutionalized in Latin America? Evidence from a comparative study in seven countries](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003427933-6/corporate-bribery-institutionalized-latin-america-gustavo-yepes-l%C3%B3pez-jose-luis-camarena-juli%C3%A1n-mauricio-cruz-pulido-luz-jeannette-quintero-campos){target="_blank"}, en el libro [Organizational Corruption, Crime and Covid-19](https://www.taylorfrancis.com/books/edit/10.4324/9781003427933/organizational-corruption-crime-covid-19-agata-stachowicz-stanusch-wolfgang-amann-christian-hauser-matthias-kleinhempel-shiv-tripathi){target="_blank"}, con Gustavo Yepes, José Luis Camarena y otros. Tailor & Francis Group. 2024.
- [Institutionalization of corporate bribery: a measurement proposal with evidence from a Latin American sample](https://www.emerald.com/insight/content/doi/10.1108/arla-04-2022-0099/full/html/){target="_blank"}, en la revista [Academia Revista Latinoamericana de Administración](https://www.emerald.com/insight/publication/issn/1012-8255){target="_blank"} (Q2); con Gustavo Yepes, José Luis Camarena y otros. Emerald Insight. 2023.
- [Who Pays for Corporate Social Responsibility?: Proposal for an Externalization Index of CSR Costs](https://link.springer.com/chapter/10.1007/978-3-031-10437-4_10){target="_blank"}, en el libro [The Route Towards Global Sustainability](https://link.springer.com/book/10.1007/978-3-031-10437-4){target="_blank"} con Gustavo Yepes y José Luis Camarena. Springer. 2023.
- [The market segmentation of higher education in Colombia reveals social inequalities](https://www.tandfonline.com/doi/pdf/10.1080/2331186X.2021.1877885?needAccess=true){target="_blank"}, en la revista [Cogent Education](https://www.tandfonline.com/journals/oaed20){target="_blank"} (Q2); con Frederick Mendoza. 2021.
- [El modelo pentadimensional aplicado a las empresas de Bogotá, Colombia](https://bdigital.uexternado.edu.co/server/api/core/bitstreams/bbf36c2b-9e0f-4f0d-a7a7-dff7b94777cc/content), en el libro [Sostenibilidad en las pymes de América Latina y el Caribe](https://publicaciones.uexternado.edu.co/gpd-sostenibilidad-en-las-pymes-de-america-latina-y-el-caribe-9789587906561.html){target="_blank"} con Gustavo Yepes, Carlos Bello y José Luis Camarena. Universidad Externado de Colombia. 2021.
 - [Diferencia de logro geolocalizado en educación presencial y a distancia en Colombia](https://redie.uabc.mx/redie/article/view/3711){target="_blank"}, en la revista [Revista Electrónica de Investigación educativa REDIE](https://redie.uabc.mx/redie){target="_blank"} (Q3); con Nicolás Arias y William Ricón. 2021.
- [Temas de investigación sobre competencias de profesores en iniciativas de actores externos en escuelas colombianas de educación básica y media](https://journal.poligran.edu.co/index.php/poliantea/article/view/2337/2209){target="_blank"}, en la revista [Poliantea](https://revistas.poligran.edu.co/index.php/poliantea){target="_blank"} con Nicolás Arias. 2021.
- [Interpreting the model is for humans, not for computers](https://medium.com/data-science/interpreting-the-model-is-for-humans-not-for-computers-9a857011ff3){target="_blank"}, with Valeria Fonseca Díaz. [Towards Datascience](https://towardsdatascience.com/){target="_blank"}. 2020.
- [Estado de las prácticas empresariales contra el soborno: primer estudio latinoamericano](https://www.pactoglobal-colombia.org/images/PDFs/LIBRO_Estudio_Antisoborno_2019.pdf){target="_blank"}, con Gustavo Yepes y otros. ISBN:  978-958-56842-3-2. Icontec Internacional. 2019.
- International CSR Policies in the Mining Sector and Their Implementation in Colombia, en el libro [Extractive Industries and Human Rights in an Era of Global Justice: New Ways of Resolving and Preventing Conflicts](https://store.lexisnexis.ca/en/categories/shop-by-jurisdiction/federal-13/extractive-industries-and-human-rights-in-an-era-of-global-justice-new-ways-of-resolving-and-preventing-conflicts--skusku-cad-6722/details){target="_blank"}, con Gustavo Yepes, Luis Bustos y Ana Devia. LexisNexis Canada. 2019.
- [Women and Men's Performace in Face-to-face, Virtual and Distance Higher Education in Colombia](https://journal.poligran.edu.co/index.php/panorama/article/download/1142/1039){target="_blank"}, con Nicolás Arias y William Ricón. Revista Panorama, 12(22), 58-69. DOI: [http://dx.doi.org/10.15765/pnrm.v12i22.1142](http://dx.doi.org/10.15765/pnrm.v12i22.1142){target="_blank"}. 2018.
- [Corrupción en Colombia: El soborno corporativo como institución](https://publicaciones.uexternado.edu.co/corrupcion-en-colombia-tomo-3-corrupcion-privada-politica-colombiana.html){target="_blank"}, con Gustavo Yepes. ISBN 978-958-772-880-4. Universidad Externado de Colombia. 2018.
 - [Factores asociados al logro educativo en estudiantes de Ciencias Económicas en modalidad presencial y a distancia en Colombia](http://hemeroteca.unad.edu.co/index.php/memorias/article/view/2890){target="_blank"}, con Nicolás Arias y William Rincón. III Congreso Mundial de Educación Superior a Distancia. 2017.
- [Estado de la Responsabilidad Social Empresarial en Colombia](http://administracion.uexternado.edu.co/PRME/memorias/Entorno%20de%20los%20Negocios%20N%2020.pdf){target="_blank"}, con Gustavo Yepes y otros. Avances de Entorno de los Negocios. N° 20, ISSN 1794 – 791X. Universidad Externado de Colombia. 2015.

***

## Proyectos de aprendizaje y reconocimientos

 - Dirección del diseño y desarrollo de la plataforma de investigación [Mamut](https://www.mmt-app.com/){target="_blank"}.
 - Dirección del diseño y desarrollo de la plataforma de evaluación y formulación de estrategias en Responsabilidad Social Empresarial [3sc4l4.co](https://www.3sc4l4.co/){target="_blank"}.
 - Paquete de R: _[Clouds](https://github.com/nebulae-co/clouds){target="_blank"}_, para la aplicación e algoritmos de agrupamiento a funciones de distribución empírica; con Daniel Moreno y Adriana Clavijo.
 - Paquete de R: _[Saber](https://github.com/nebulae-co/saber){target="_blank"}_, para la disponibilidad de los datos de la prueba Saber 11; con Daniel Moreno y Adriana Clavijo. 
 - Paquete de R: _[Colmaps](https://github.com/nebulae-co/colmaps){target="_blank"}_, para la elaboración de mapas de Colombia, con departamentos y municipios; con Daniel Moreno y Adriana Clavijo.
 - _Logro Educativo en Estudiantes de Ciencias Económicas en Educación Superior Presencial y Virtual_. Proyecto ganador en la [Convocatoria ICFES 2015](https://www.icfes.gov.co/web/guest/resultados-de-investigaciones-2015){target="_blank"}, con Nicolás Arias y William Rincón.
 - III Congreso Internacional "Estudios en Organizaciones Públicas, Privadas y Sociales en América Latina y El Caribe". Ponencia titulada: _Logro Educativo y Evidencias de sus posibles Factores Asociados en Estudiantes de Ciencias Económicas en Modalidadd Presencial y Virtual_, con Nicolás Arias y William Rincón.
 - 25 Simposio Internacional de Estadística 2015. Ponencia titulada: _[Un micro-mapa de Colombia](http://nebulae-co.github.io/colmaps/micromapa){target="_blank"}_, con Daniel Moreno y Adriana Clavijo.
 - 24 Simposio Internacional de Estadística 2014. Ponencia titulada: _Uso De Metaheurísticas en Estimación Nadaraya-Watson con Aplicación a Cirugía Refractiva_.
 - 24 Simposio Internacional de Estadística 2014. Ponencia titulada: _Algoritmos de Agrupación en Diseño de Experimentos. Una Propuesta No Paramétrica_.
 - Mejor puntaje de su carrera a nivel nacional en el examen Saber Pro en su promoción, 2013.
 - Beca completa Universidad Nacional de Colombia por mejor puntaje de ingreso, 2009.
 - Mejor puntaje en el examen del ICFES en su promoción y Mención Honorífica por desarrollo artístico, 2002.
 
***


