---
title: "Experiencia laboral"
---

***

## Universidad Nacional de Colombia

**Dirección de diplomados en Ciencia de Datos e Inteligencia de Negocios.** Diseño de programa curricular del diplomado, selección de contenidos, docentes y materiales de cada curso. Coordinación de horarios, espacios, softwares y detalles de implementación. 

Análisis estratégico del mercado y los canales de comunicación. Implementación de una experiencia de aprendizaje inmersivo centrada en los estudiantes.

Es posible acceder a los detalles de los diplomados:

 - [Diplomado en Análisis de datos](http://www.fce.unal.edu.co/media/files/PEC/Formacion_a_escala/2019/III_TRIMESTRE/ficha_analisis_de_datos.pdf){target="_blank"}
 - [Diplomado en Ciencia de datos](http://fce.unal.edu.co/pec/diplomado-en-ciencia-de-datos/){target="_blank"}
 - [Diplomado en Inteligencia de Negocios](http://fce.unal.edu.co/pec/diplomado-en-inteligencia-de-negocios/){target="_blank"}

Datos del proyecto:

 - Rol: Director
 - Jefe inmediato: [Sylvia María Valenzuela](https://www.linkedin.com/in/sylvia-maria-valenzuela-tovar-55648515b/)
 - Contacto: uniei_fcebog@unal.edu.co, 3165000 Ext 12305/12306/12307.
 - Agosto 2019 - Actualmente

***

## Universidad Externado de Colombia

**Asesoría estadística en investigación** Diseño metodológico, recolección de la información, estimación de parámetros, tamaños de muestra, diseño de formularios, desarrollo de encuestas, desarrollo de plataformas web, diseños muestrales y análisis cuantitativos, entre otras, para los estudios:

 - Índice de Institucionalización del Soborno en Latino América y el Caribe. Publicado en el libro [Estado de las prácticas empresariales contra el soborno: primer estudio latimoamericano](https://www.pactoglobal-colombia.org/images/PDFs/LIBRO_Estudio_Antisoborno_2019.pdf){target="_blank"}.
 - Estudio Nacional de Transparencia 2018. Informe publicado por Transparencia por Colombia.
 - Soborno Corporativo como Institución. Publicado en el libro [Corrupción en Colombia](https://publicaciones.uexternado.edu.co/corrupcion-en-colombia-tomo-3-corrupcion-privada-politica-colombiana.html){target="_blank"}.
 - Estudio Nacional de Transparencia 2016. Informe publicado por Transparencia por Colombia.

Adicionalmente intervenciones breves y colaboraciones para algunas tesis de maestría y artículos de investigación.
 
 - Rol: Docente
 - Jefe inmediato: [Gustavo Yepes](https://www.linkedin.com/in/gustavoyepes-lopez-82049713/){target="_blank"}
 - Contacto: gustavo.yepes@uexternado.edu.co
 - Abril 2016 - Actualmente.

***


## Ministerio de las Tecnologías de la Información y las Comunicaciones

**Dirección del equipo de Ciencia de Datos.** Puesta en marcha del procedimiento de analítica. Propuesta, ejecución, evaluación y retroalimentación de proyectos de Ciencia de Datos para el análisis de la información contenida en los sistemas de información de la entidad que incorporen el uso de herramientas de analítica de grandes volúmenes de información (Big Data), en cumplimiento de todo lo relacionado con las obligaciones legales, contractuales y regulatorias de las empresas prestadoras de servicios móvil, no móvil, televisión, radiodifusión sonora y postal.

 - Rol: Jefe de Ciencia de Datos
 - Jefe inmediato: Nicolás Almeyda
 - Contacto: nalmeyda@mintic.gov.co 
 - Agosto 2020 - Diciembre 2021.

***

## Aseguradora de Riesgos Laborales Colmena

**Asesoría estadística en salud y seguridad en el trabajo para Sanitas Internacional.** Implementación de sistemas de información, diseño de bases de datos, recolección y análisis de datos de casos médico laborales y medición de indicadores de impacto en salud ocupacional. Asesoría a 3 Sistemas de Vigilancia Epidemiológica: Psicosocial, Ergonómico y Riesgo Biológico e implementación de algoritmos de identificación de ausentismo frecuente.

 - Rol: Asesor de Prevención por Proyecto
 - Jefe inmediato: [Mario Garzón](https://www.linkedin.com/in/mario-garz%C3%B3n-lawton-82207a25/){target="_blank"}
 - Contacto: mfgarzon@colsanitas.com
 - Febrero 2014 – Febrero 2015

***

## Optiláser

**Asesoría estadística en investigación.** Diseño metodológico, análisis estadístico, visualización e interpretación de resultados cuantitativos en salud visual.

 - Rol: Asesor estadístico en investigación científica.
 - Jefe inmediato: [María Victoria Báez](https://www.linkedin.com/in/mar%C3%ADa-victoria-b%C3%A1ez-gonz%C3%A1lez-34149848/){target="_blank"}
 - Contacto: vicky.baez@optilaser.com.co
 - Junio 2011- Enero 2013

***

```{r, child="footer.rmd"}
```

