---
title: "Experiencia laboral"
---

***

## Ministerio de las Tecnologías de la Información y las Comunicaciones

**Dirección del equipo de Ciencia de Datos.** Puesta en marcha del procedimiento de analítica. Propuesta, ejecución, evaluación y retroalimentación de proyectos de Ciencia de Datos para el análisis de la información contenida en los sistemas de información de la entidad que incorporen el uso de herramientas de analítica de grandes volúmenes de información (Big Data), en cumplimiento de todo lo relacionado con las obligaciones legales, contractuales y regulatorias de las empresas prestadoras de servicios móvil, no móvil, televisión, radiodifusión sonora y postal.

 - Rol: Jefe de Ciencia de Datos
 - Jefe inmediato: Nicolás Almeyda
 - Contacto: nalmeyda@mintic.gov.co
 - Agosto 2020 - Diciembre 2021.

***

## Institución Universitaria Politécnico Grancolombiano

**Consultoría en minería de datos** Diseño y desarrollo de un sistema de distancias entre asignaturas para la optimización del portafolio de asignaturas en el marco de mejoras a la plataforma institucional.

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cilente (representante): [Ana Cristina Miranda](https://www.linkedin.com/in/ana-cristina-miranda-cárdenas-20273b114/){target="_blank"}.
 - Contacto: amiranda@poligran.edu.co.
 - Febrero 2018 - Mayo 2018.

**Consultoría estadística en investigación** Diseño metodológico, recolección de la información y análisis estadístico para los estudios _Análisis de iniciativas de formación docente según antecedentes de investigación internacional sobre competencias docentes_, _Preparación de bases de datos de evaluaciones internacionales de PISA 2015_ y _Revisión de antecedentes de comparación entre educación presencial y virtual_.

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cliente (representante): [Nicolás Arias](https://www.linkedin.com/in/nicolas-arias-velandia-706719ab/){target="_blank"}.
 - Contacto: nariasv@poligran.edu.co
 - Septiembre de 2017 - Noviembre 2017.


**Consultoría estadística en investigación** Diseño metodológico, recolección de la información y análisis estadístico para el estudio _Estudio de la Oferta y la Demanda de Programas Académicos de Educación Superior en Colombia_.

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cliente (representante): [Frederick Andrés Mendoza](https://www.linkedin.com/in/frederick-andres-mendoza-lozano-7a773133/){target="_blank"}.
 - Contacto: famendozal23@gmail.com 
 - Mayo 2017 - Agosto 2017.

**Consultoría estadística en investigación** Diseño metodológico, recolección de la información y análisis estadístico para el estudio _Logro Educativo en Estudiantes de Ciencias Económicas en Educación Superior Presencial y Virtual_. Proyecto ganador en la [Convocatoria ICFES 2015](https://www.icfes.gov.co/web/guest/resultados-de-investigaciones-2015){target="_blank"}. 

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cliente (representante): [Nicolás Arias](https://www.linkedin.com/in/nicolas-arias-velandia-706719ab/){target="_blank"}.
 - Contacto: nariasv@poligran.edu.co
 - Agosto 2016 - Diciembre 2016.

***

## Power Data SAS

**Modelos de pronóstico de deserción para Claro Hogares** Planeación y direccionamiento en procesos de medición y pronóstico para el área de Analytics. Responsable de los procesos de diseño, ajuste, estimación e implementación de modelos y algoritmos estadísticos, de aprendizaje automático y de minería de datos.

Datos del proyecto:

 - Rol: Consultor Senior
 - Cliente (representante): [Nicolás Aristizabal](https://www.linkedin.com/in/niaristizaballo/){target="_blank"}.
 - nicolas.aristizabal.eci@gmail.com
 - Noviembre 2015 - Marzo 2016

***

## Aseguradora de Riesgos Laborales Colmena

**Asesoría estadística en salud y seguridad en el trabajo para Sanitas Internacional.** Implementación de sistemas de información, diseño de bases de datos, recolección y análisis de datos de casos médico laborales y medición de indicadores de impacto en salud ocupacional. Asesoría a 3 Sistemas de Vigilancia Epidemiológica: Psicosocial, Ergonómico y Riesgo Biológico e implementación de algoritmos de identificación de ausentismo frecuente.

 - Rol: Asesor de Prevención por Proyecto
 - Jefe inmediato: [Mario Garzón](https://www.linkedin.com/in/mario-garz%C3%B3n-lawton-82207a25/){target="_blank"}
 - Contacto: mfgarzon@colsanitas.com
 - Febrero 2014 – Febrero 2015

***

## Optiláser

**Asesoría estadística en investigación.** Diseño metodológico, análisis estadístico, visualización e interpretación de resultados cuantitativos en salud visual.

 - Rol: Asesor estadístico en investigación científica.
 - Jefe inmediato: [María Victoria Báez](https://www.linkedin.com/in/mar%C3%ADa-victoria-b%C3%A1ez-gonz%C3%A1lez-34149848/){target="_blank"}
 - Contacto: vicky.baez@optilaser.com.co
 - Junio 2011- Enero 2013

***

