---
title: "Asesorías"
---

***

Desde el año 2010 se lleva a cabo labor contínua e independiente de asesoría estadística en investigación que no se detiene en ningún momento. Este ejercicio tiene como objetivo enfrentar problemas de distintas áreas y dar respuesta desde el análisis de datos a preguntas de investigación de diversa índole.

***

### 2020 - actualmente

**Influencia del nivel tecnológico en la productividad y competitividad de apicultores de Cundinamarca**

  - [Rodrigo Chaves Ladino.](https://www.linkedin.com/in/rodrigo-chaves-ladino/){target="_blank"}

  - Tesis de grado para optar al título de Magíster en Gestión y desarrollo rural. Facultad de ciencias agrarias. Universidad Nacional de Colombia. 2022.


**Estimación de los costos directos médicos netos de la atención de cáncer de mama en el sistema general de seguridad social en salud en Colombia**

  - José Ricardo Urrego Novoa.

  - Tesis de grado para optar al título de PhD. en Ciencias Farmacéuticas. Universidad Nacional de Colombia. Colombia, 2020.

***

### 2015 - 2019

**[Articulación de la educación media con la educación superior en Bogotá Colombia: implicaciones pedagógicas en el contexto local](http://e-spacio.uned.es/fez/eserv/tesisuned:ED-Pg-Educac-Erivera/RIVERA_BOTELLO__Elias_tesis.pdf){target="_blank"}**

  - Elías Rivero Botello.

  - Tesis de grado para optar al título de PhD. en Educación. Universidad Nacional de Educación a Distancia. 2019.

**[Conductas sexuales de riesgo en jóvenes universitarios: representaciones sociales y satisfacción sexual](https://repositorio.unal.edu.co/handle/unal/76716){target="_blank"}**

  - Heidi Marcela Castro Hernández.

  - Tesis de grado para Maestría en Psicología Clínica. Universidad Nacional de Colombia. 2019.

**[Costo-efectividad del tratamiento agresivo de la artritis reumatoide temprana con medicamentos modificadores de la enfermedad convencionales comparados con inhibidores del factor de necrosis tumoral alfa en una cohorte de pacientes colombianos](https://repositorio.unal.edu.co/handle/unal/63676){target="_blank"}**

  - [Jorge Augusto Díaz.](https://www.linkedin.com/in/jorge-diaz-rojas-0106b369/){target="_blank"}

  - Tesis de grado para optar al título de PhD. en Ciencias Farmacéuticas. Universidad Nacional de Colombia. 2017.

**[Evaluación del factor de rendimiento de los jueces en Colombia](https://repository.unilibre.edu.co/handle/10901/11431){target="_blank"}**

  - Omar Edgar Borja Soto.

  - Tesis de grado de Maestría en Derecho Administrativo, Universidad Libre de Colombia. 2016.

**[Relación entre el programa académico de educación superior que estudian jóvenes de Bogotá entre 18 y 24 años y su actitud frente al ahorro, el endeudamiento y el dinero](https://biblioteca.konradlorenz.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=22723&query_desc=an%3A798){target="_blank"}**
   
  - [Heleonora Sánchez Castillo.](https://www.linkedin.com/in/heleonorasanchezc/){target="_blank"}
  
  - Trabajo de grado para optar título de Magister en Psicología del Consumidor. Fundación Universitaria Konrad Lorenz. 2016.

**[Modelo de ciclos socio-tecnológicos para productos social y ambientalmente responsables. Caso: Corte intensivo de rosas con energía humana](https://www.tdx.cat/handle/10803/392638?locale-attribute=es){target="_blank"}**

  - [Gabriel García Acosta.](https://www.linkedin.com/in/gabriel-garc%C3%ADa-acosta-33881153/){target="_blank"}

  - Trabajo de grado para optar título de Doctor en Proyectos de Innovación Tecnológica en la Ingeniería de Productos y Procesos, Universidat Politècnica de Catalunya. 2015.

**La Responsabilidad Social Empresarial en Colombia: Caracterización de las Prácticas de RSE frente a la Teoría de los Costos Sociales y su Relación con el Negocio**

  - [Gustavo Yépez.](https://www.linkedin.com/in/gustavoyepes/){target="_blank"} 

  - Trabajo de grado para optar título de Doctor en Ciencias Empresariales, Universidad Antonio de Nebrija. 2015.

**[Evaluación de los efectos de FCS-304 en modelos de depresión en roedores](https://repositorio.unal.edu.co/handle/unal/54369){target="_blank"}**

  - Laura Mercedes Moreno Hernández.

  - Trabajo de grado para optar título de M.Sc. en Farmacología, Universidad Nacional de Colombia. 2015

**[Integración de la gestión de la seguridad y salud en el trabajo en la responsabilidad social. Estudio de caso en cinco empresas bogotanas.](https://repositorio.unal.edu.co/handle/unal/54640){target="_blank"}**


  - [Carolina Hernández Macías.](https://www.linkedin.com/in/carolina-hernandez-macias-49863275/){target="_blank"}

  - Trabajo de grado para optar el título de Magister en Salud y Seguridad en el Trabajo, Universidad Nacional de Colombia. 2015.

***

### 2010 - 2014

**[Una descripción matemática del recambio evolutivo de los ARNt en el género Drosophila](https://repositorio.unal.edu.co/handle/unal/73129){target="_blank"}**

  - [Liliana Constanza Romero.](https://www.linkedin.com/in/liliana-constanza-romero/){target="_blank"}

  - Trabajo de grado para optar el título de Magister en Ciencias - Matemática Aplicada, Universidad Nacional de Colombia. 2014.

**[Refracción en lactantes de 6 a 12 meses  usando la técnica no ciclopégica y ciclopégica con  tropicamida al 1% ciclopentolato al 1%, estudio realizado en bogotá 2012-2014](https://ciencia.lasalle.edu.co/cgi/viewcontent.cgi?article=1043&context=maest_ciencias_vision){target="_blank"}**

  - Natali Gutierrez.

  - Trabajo de grado para optar el título de Magister en Ciencias de la Visión, Universidad de La Salle. 2014.

**[Impacto de la cosecha de palmito sobre la estructura y dinámica poblacional de Euterpe oleracea en la Costa Pacífica colombiana](http://library.wur.nl/WebQuery/wurpubs/490413){target="_blank"}**

  - Martha Isabel Vallejo.

  - Trabajo de grado para optar el título de PhD en Ciencias - Biología, Universidad Nacional de Colombia. 2013.

**Hallazgos acelerométricos  antes, durante y después de la exposición a etanol en pacientes con temblor esencial**

  - Lorena Arroyo.

  - Trabajo de grado para optar el título de Magister en Neurocioencias, Universidad Nacional de Colombia. Tesis meritoria. 2013.

**Cambios en la sintomatología, película lagrimal y superficie ocular  después del tratamiento con ciclosporina al 1% y carboximetilcelulosa 0.5%, en el síndrome de ojo seco  moderado y severo**

  - Alejandra Mendivelso Suárez.

  - Trabajo de grado para optar el título de Magister en Ciencias de la Visión, Universidad de La Salle. 2013.

**[Relación entre violencia de pareja contra la mujer y aparición de depresión en el postparto](https://repositorio.unal.edu.co/handle/unal/11473){target="_blank"}**

  - Edna Janneth Ramirez Bonilla.

  - Tesis presentada como requisito para optar al título de Magister en Enfermería. Universidad Nacional de Colombia. 2012.

**Infección de vías urinarias: estudio costo-enfermedad y caracterización demográfica en una clínica de tercer nivel en Chía, Colombia**

  - Hernando Andrés Olaya MD. y Mauricio Hernández Quintana MD.

  - Tesis de Maestría en Farmacología presentada en la Universidad de la Sabana. 2011.

**[Evaluación de las aberraciones corneales y oculares mediante el índice RMS de alto orden con dos lentes de contacto blandos asfericos en pacientes con astigmatismo miópico bajo](https://docplayer.es/docview/70/63889504/#file=/storage/70/63889504/63889504.pdf){target="_blank"}**

  - Elizabeth Suarez Piscotti y Natali Rodriguez.

  - Tesis de pregrado en Optometría presentada en la Universidad de la Salle. 2011.

***


