---
title: "Proyectos"
---

***

En esta sección se presentan algunos proyectos realizados de manera independiente. La dirección de proyectos en ciencia de datos es un camino lleno de retos. Aunque el aprendizaje de estos proyectos es inmenso, también es necesario reconocer que falta mucho por recorrer.


***

## Universidad Externado de Colombia

**Diseño y desarrollo de software.** Creación y dirección de un equipo de diseño y desarrollo para la plataforma de Responsabilidad Social Empresarial 3SC4L4. Dirección completa del proyecto, conformación del equipo, toma de requerimientos, backlog, historias de usuario, producto mínimo viable e iteraciones posteriores.

Es posible acceder al producto final en [3sc4l4.co](https://www.3sc4l4.co/){target="_blank"}


Datos del proyecto:

 - Rol: Director
 - Cliente: [Programa Primeros Pasos en Responsabilidad Social Empresarial](https://www.uexternado.edu.co/administracion-de-empresas/programa-primeros-pasos-en-responsabilidad-social-empresarial/){target="_blank"}
 - Cliente (representante): [Gustavo Yepes](https://www.linkedin.com/in/gustavoyepes-lopez-82049713/){target="_blank"}.
 - Contacto: gustavo.yepes@uexternado.edu.co

***

## Universidad Nacional de Colombia

**Dirección del diplomado de Ciencia de Datos.** Diseño de programa curricular del diplomado, selección de contenidos, docentes y materiales de cada curso. Coordinación de horarios, espacios, softwares y detalles de implementación. 

Análisis estratégico del mercado y los canales de comunicación. Implementación de una experiencia de aprendizaje inmersivo centrada en los estudiantes.

Es posible acceder a las diferentes versiones del diplomado en:

 - [Diplomado de Análisis de datos](http://www.fce.unal.edu.co/media/files/PEC/Formacion_a_escala/2019/III_TRIMESTRE/ficha_analisis_de_datos.pdf){target="_blank"}: Octubre 2019 - Diciembre 2019.
 - [Diplomado de Ciencia de datos](http://www.fce.unal.edu.co/media/files/PEC/Diplomados_2020/Diplomado_en_Ciencia_de_Datos.pdf){target="_blank"}: Septiembre 2020 - Diciembre 2020.
 - [Diplomado de Ciencia de datos](http://www.fce.unal.edu.co/media/files/PEC/Diplomados_2021/Ciencia_de_Datos_VFA1S.pdf){target="_blank"}: Febrero 2021 - Junio 2021.

Datos del proyecto:

 - Rol: Director
 - Cliente: [Programa de Educación Continua y Permanente](http://www.fce.unal.edu.co/pec.html){target="_blank"}.
 - Contacto: uniei_fcebog@unal.edu.co, 3165000 Ext 12305/12306/12307.

***

## Platzi

**Docencia.** Diseño del sylabus, presentación, lecturas, código y demás materiales correspondientes al curso de Estadística Inferencial.

Es posible acceder al producto final en [Estadística Inferencial con R](https://platzi.com/cursos/estadistica-inferencial/){target="_blank"}.

Datos del proyecto:

 - Rol: Profesor
 - Cliente (representante): [Enrique Devars](https://www.edevars.com/){target="_blank"}.
 - Contacto: devars@platzi.com
 - Julio 2020.

***

## Institución Universitaria Politécnico Grancolombiano

**Consultoría en minería de datos** Diseño y desarrollo de un sistema de distancias entre asignaturas para la optimización del portafolio de asignaturas en el marco de cambio de plataforma institucional.

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cilente (representante): [Ana Cristina Miranda](https://www.linkedin.com/in/ana-cristina-miranda-cárdenas-20273b114/){target="_blank"}.
 - Contacto: amiranda@poligran.edu.co.
 - Febrero 2018 - Abril 2018.

**Consultoría estadística en investigación** Diseño metodológico, recolección de la información y análisis estadístico para el estudio _Estudio de la Oferta y la Demanda de Programas Académicos de Educación Superior en Colombia_.

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cliente (representante): [Frederick Andrés Mendoza](https://www.linkedin.com/in/frederick-andres-mendoza-lozano-7a773133/){target="_blank"}.
 - Contecto: famendozal23@gmail.com 
 - Mayo 2017 - Agosto 2017.

**Consultoría estadística en investigación** Diseño metodológico, recolección de la información y análisis estadístico para el estudio _Logro Educativo en Estudiantes de Ciencias Económicas en Educación Superior Presencial y Virtual_. Proyecto ganador en la [Convocatoria ICFES 2015](https://www.icfes.gov.co/web/guest/resultados-de-investigaciones-2015){target="_blank"}. 

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cliente (representante): [Nicolás Arias](https://www.linkedin.com/in/nicolas-arias-velandia-706719ab/){target="_blank"}.
 - Contacto: nariasv@poligran.edu.co
 - Agosto 2016 - Diciembre 2016.

***

## Fundación para la Educación y el Desarrollo Social FES - Ministerio de Tecnologías de la Información y Comunicaciones

**Índice Multidimensional de Brecha Digital Regional** Diseño metodológico, encuesta a hogares, análisis de indicadores, diseño de un índice multidimensional para el estudio Proyecto de Cierre de Brecha Digital Regional.

Datos del proyecto:

 - Rol: Investigador
 - Cliente (representante): [Diana María Duarte](https://www.linkedin.com/in/diana-duarte-g%C3%B3mez-301a88116/){target="_blank"}.
 - Contacto: dm.duarte29@uniandes.edu.co
 - Enero de 2018 - Julio de 2018.
  
***

## Internet Services Latam

**Consultoría estadística Especializada** Diseño y desarrollo de un modelo de pronóstico de demanda día - hora - punto de venta para la app Mercadoni. Preparación y análisis de datos históricos de ventas de retail; conceptualización del modelo Parzen Window para demanda, desarrollo del código e implementación del modelo.

Datos del proyecto:

 - Rol: Consultor Estadístico Especializado
 - Cliente (representante): [Daniel Moreno](https://www.linkedin.com/in/demorenoc/){target="_blank"}.
 - Contacto: troybros@gmail.com 
 - Diciembre 2017 - Enero 2018.

***

## Power Data SAS

**Modelos de pronóstico de deserción para Claro Hogares** Planeación y direccionamiento en procesos de medición y pronóstico para el área de Analytics. Responsable de los procesos de diseño, ajuste, estimación e implementación de modelos y algoritmos estadísticos, de aprendizaje automático y de minería de datos.

Datos del proyecto:

 - Rol: Consultor Senior
 - Cliente (representante): [Nicolás Aristizabal](https://www.linkedin.com/in/niaristizaballo/){target="_blank"}.
 - nicolas.aristizabal.eci@gmail.com
 - Noviembre 2015 - Marzo 2016

***

```{r, child="footer.rmd"}
```

