---
title: "Experiencia docente"
---

***


## Universidad Nacional de Colombia

**Dirección de diplomados en Ciencia de Datos e Inteligencia de Negocios.** Diseño curricular del diplomado, selección de contenidos, docentes y materiales de cada curso. Coordinación de horarios, espacios, softwares y detalles de implementación. 

Análisis estratégico del mercado y los canales de comunicación. Implementación de una experiencia de aprendizaje inmersivo centrada en los estudiantes.

Es posible acceder a los detalles de los diplomados:

 - [Diplomado en Análisis de datos](http://www.fce.unal.edu.co/media/files/PEC/Formacion_a_escala/2019/III_TRIMESTRE/ficha_analisis_de_datos.pdf){target="_blank"}
 - [Diplomado en Ciencia de datos](http://fce.unal.edu.co/pec/diplomado-en-ciencia-de-datos/){target="_blank"}
 - [Diplomado en Inteligencia de Negocios](http://fce.unal.edu.co/pec/diplomado-en-inteligencia-de-negocios/){target="_blank"}

Datos del proyecto:

 - Rol: Director
 - Agosto 2019 - Actualmente

Adicionalmente,

 - _Elaboración de informes estadísticos_, curso de extensión dirigido a funcionarios de la Veeduría Distrital, Programa de Educación Continua (PEC), Facultad de Ciencias Económicas. Universidad Nacional de Colombia. 2019. 
 - _Minería de Datos_, curso de extensión dirigido a funcionarios del Banco Agrario, Programa de Educación Continua (PEC), Facultad de Ciencias Económicas. Universidad Nacional de Colombia. 2019. 
 - _Minería de Datos_ curso de extensión en el marco del [Diplomado en Inteligencia de Mercados](http://www.fce.unal.edu.co/media/files/PEC/cursos/Diplomados_2019/ficha_diplomado_inteligencia_de_mercados.pdf){target="_blank"}, Programa de Educación Continua (PEC), Facultad de Ciencias Económicas. Universidad Nacional de Colombia. 2019. 
 - _Analítica de datos en mercadeo_, curso de extensión en el marco del [Diplomado en Inteligencia de Mercados](http://www.fce.unal.edu.co/media/files/PEC/cursos/Diplomados_2019/ficha_diplomado_inteligencia_de_mercados.pdf){target="_blank"}, Programa de Educación Continua (PEC), Facultad de Ciencias Económicas Universidad Nacional de Colombia. 2019. 
 - _Introducción a R_, curso de extensión en el marco del [Diplomado de Procesamiento y Análisis de Datos](http://www.fce.unal.edu.co/media/files/PEC/cursos/cursos_2019/Ficha_procesamiento_y_analisis_de_datos_15012019.pdf){target="_blank"}, Programa de Educación Continua (PEC), Facultad de Ciencias Económicas Universidad Nacional de Colombia 2019.


***

## Universidad Externado de Colombia

**Profesor de tiempo completo** en la Facultad de Ciencias Sociales y Humanas (FCSH). Diseño metodológico, recolección de la información, estimación de parámetros, tamaños de muestra, diseño de formularios, desarrollo de encuestas, desarrollo de plataformas web, diseños muestrales y análisis cuantitativos, entre otras, para diversos estudios.

 - Rol: Docente
 - Abril 2016 - Actualmente
 
Adicionalmente,
 
**Docente en cursos de pregrado y postgrado** Esta labor comprende el construcción e implementación de cursos para distintos programas de pregrado y postgrado. Diseño y producción de materiales pedagógicos. Diseño y aplicación de herramientas de evaluación en los cursos:

 - _Investigación cuantitativa de mercados_. Maestría en mercadeo. Facultad de administración de empresas. Universidad Externado de Colombia. 2020.
 - _Analítica de negocios_. Maestría en Gerencia Estratégica de Tecnologías de Información. Facultado de Administración de Empresas. Universidad Externado de Colombia. 2020.
 - _Modelaciones complejas_. Maestría en Neurociencia Social. Facultado de Ciencias Sociales y Humanas. Universidad Externado de Colombia. 2025.


***

## Platzi

**Curso de Estadística Inferencial** Diseño del sylabus, presentación, lecturas, código y demás materiales correspondientes al curso.

Es posible acceder al producto final en [Estadística Inferencial con R](https://platzi.com/cursos/estadistica-inferencial/){target="_blank"}.

 - Rol: Profesor
 - Julio 2020.

***

## Publicaciones

- [Predictive modeling of the ROX index in high-flow nasal cannula use for COVID-19 ARDS: Panel and functional data approaches](https://www.sciencedirect.com/science/article/abs/pii/S095461112500486X){target="_blank"}, en la revista [Respiratory Medicine](https://www.sciencedirect.com/journal/respiratory-medicine){target="_blank"} (Q1), con Diana Sotelo, Jorge Medina-Parra, Ricardo Merchán-Chaverra y otros. ScienceDirect. 2025.
- [How Are HEIs Coping With the PRME Indicator System of University Social Responsibility? Evidence From Colombia](https://onlinelibrary.wiley.com/doi/abs/10.1111/hequ.70052){target="_blank"}, en la revista [Higher Education Quarterly](https://onlinelibrary.wiley.com/journal/14682273){target="_blank"} (Q1), con Gustavo Yepes, José Luis Camarena y otros. Wiley. 2025.
- [Does CSR Contribute to Sustainable Development? Characterization of CSR in Colombian Companies](https://link.springer.com/chapter/10.1007/978-3-031-81469-3_4){target="_blank"}, en el libro [Integrating Environmental Sustainability and Corporate Social Responsibility: A Move Beyond Profit](https://link.springer.com/book/10.1007/978-3-031-81469-3){target="_blank"}, con Gustavo Yepes y José Luis Camarena. Springer. 2025.
- [Are Firms Strategically Engaging in CSR? An Exploratory Study of SCSR Dimensions in an Emerging Market](https://link.springer.com/chapter/10.1007/978-3-031-81469-3_6){target="_blank"}, en el libro [Integrating Environmental Sustainability and Corporate Social Responsibility: A Move Beyond Profit](https://link.springer.com/book/10.1007/978-3-031-81469-3){target="_blank"}, con Gustavo Yepes y José Luis Camarena. Springer. 2025.
- [Observaciones con respecto a la ciencia abierta](https://revistas.uexternado.edu.co/index.php/contad/article/view/9933/17422){target="_blank"} carta al editor en la revista [Apuntes contables](https://revistas.uexternado.edu.co/index.php/contad/){target="_blank"}. Universidad Externado de Colombia. 2025.
- [Is corporate bribery institutionalized in Latin America? Evidence from a comparative study in seven countries](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003427933-6/corporate-bribery-institutionalized-latin-america-gustavo-yepes-l%C3%B3pez-jose-luis-camarena-juli%C3%A1n-mauricio-cruz-pulido-luz-jeannette-quintero-campos){target="_blank"}, en el libro [Organizational Corruption, Crime and Covid-19](https://www.taylorfrancis.com/books/edit/10.4324/9781003427933/organizational-corruption-crime-covid-19-agata-stachowicz-stanusch-wolfgang-amann-christian-hauser-matthias-kleinhempel-shiv-tripathi){target="_blank"}, con Gustavo Yepes, José Luis Camarena y otros. Tailor & Francis Group. 2024.
- [Institutionalization of corporate bribery: a measurement proposal with evidence from a Latin American sample](https://www.emerald.com/insight/content/doi/10.1108/arla-04-2022-0099/full/html/){target="_blank"}, en la revista [Academia Revista Latinoamericana de Administración](https://www.emerald.com/insight/publication/issn/1012-8255){target="_blank"} (Q2); con Gustavo Yepes, José Luis Camarena y otros. Emerald Insight. 2023.
- [Who Pays for Corporate Social Responsibility?: Proposal for an Externalization Index of CSR Costs](https://link.springer.com/chapter/10.1007/978-3-031-10437-4_10){target="_blank"}, en el libro [The Route Towards Global Sustainability](https://link.springer.com/book/10.1007/978-3-031-10437-4){target="_blank"} con Gustavo Yepes y José Luis Camarena. Springer. 2023.
- [The market segmentation of higher education in Colombia reveals social inequalities](https://www.tandfonline.com/doi/pdf/10.1080/2331186X.2021.1877885?needAccess=true){target="_blank"}, en la revista [Cogent Education](https://www.tandfonline.com/journals/oaed20){target="_blank"} (Q2); con Frederick Mendoza. 2021.
- [El modelo pentadimensional aplicado a las empresas de Bogotá, Colombia](https://bdigital.uexternado.edu.co/server/api/core/bitstreams/bbf36c2b-9e0f-4f0d-a7a7-dff7b94777cc/content), en el libro [Sostenibilidad en las pymes de América Latina y el Caribe](https://publicaciones.uexternado.edu.co/gpd-sostenibilidad-en-las-pymes-de-america-latina-y-el-caribe-9789587906561.html){target="_blank"} con Gustavo Yepes, Carlos Bello y José Luis Camarena. Universidad Externado de Colombia. 2021.
 - [Diferencia de logro geolocalizado en educación presencial y a distancia en Colombia](https://redie.uabc.mx/redie/article/view/3711){target="_blank"}, en la revista [Revista Electrónica de Investigación educativa REDIE](https://redie.uabc.mx/redie){target="_blank"} (Q3); con Nicolás Arias y William Ricón. 2021.
- [Temas de investigación sobre competencias de profesores en iniciativas de actores externos en escuelas colombianas de educación básica y media](https://journal.poligran.edu.co/index.php/poliantea/article/view/2337/2209){target="_blank"}, en la revista [Poliantea](https://revistas.poligran.edu.co/index.php/poliantea){target="_blank"} con Nicolás Arias. 2021.
- [Interpreting the model is for humans, not for computers](https://medium.com/data-science/interpreting-the-model-is-for-humans-not-for-computers-9a857011ff3){target="_blank"}, with Valeria Fonseca Díaz. [Towards Datascience](https://towardsdatascience.com/){target="_blank"}. 2020.
- [Estado de las prácticas empresariales contra el soborno: primer estudio latinoamericano](https://www.pactoglobal-colombia.org/images/PDFs/LIBRO_Estudio_Antisoborno_2019.pdf){target="_blank"}, con Gustavo Yepes y otros. ISBN:  978-958-56842-3-2. Icontec Internacional. 2019.
- International CSR Policies in the Mining Sector and Their Implementation in Colombia, en el libro [Extractive Industries and Human Rights in an Era of Global Justice: New Ways of Resolving and Preventing Conflicts](https://store.lexisnexis.ca/en/categories/shop-by-jurisdiction/federal-13/extractive-industries-and-human-rights-in-an-era-of-global-justice-new-ways-of-resolving-and-preventing-conflicts--skusku-cad-6722/details){target="_blank"}, con Gustavo Yepes, Luis Bustos y Ana Devia. LexisNexis Canada. 2019.
- [Women and Men's Performace in Face-to-face, Virtual and Distance Higher Education in Colombia](https://journal.poligran.edu.co/index.php/panorama/article/download/1142/1039){target="_blank"}, con Nicolás Arias y William Ricón. Revista Panorama, 12(22), 58-69. DOI: [http://dx.doi.org/10.15765/pnrm.v12i22.1142](http://dx.doi.org/10.15765/pnrm.v12i22.1142){target="_blank"}. 2018.
- [Corrupción en Colombia: El soborno corporativo como institución](https://publicaciones.uexternado.edu.co/corrupcion-en-colombia-tomo-3-corrupcion-privada-politica-colombiana.html){target="_blank"}, con Gustavo Yepes. ISBN 978-958-772-880-4. Universidad Externado de Colombia. 2018.
 - [Factores asociados al logro educativo en estudiantes de Ciencias Económicas en modalidad presencial y a distancia en Colombia](http://hemeroteca.unad.edu.co/index.php/memorias/article/view/2890){target="_blank"}, con Nicolás Arias y William Rincón. III Congreso Mundial de Educación Superior a Distancia. 2017.
- [Estado de la Responsabilidad Social Empresarial en Colombia](http://administracion.uexternado.edu.co/PRME/memorias/Entorno%20de%20los%20Negocios%20N%2020.pdf){target="_blank"}, con Gustavo Yepes y otros. Avances de Entorno de los Negocios. N° 20, ISSN 1794 – 791X. Universidad Externado de Colombia. 2015.

***

